# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-hpa-app
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: keda-hpa-app
  template:
    metadata:
      labels:
        app: keda-hpa-app
    spec:
      containers:
      - image: sergio21/keda-hpa-app:0.0.1
        name: keda-hpa-app
        resources:
          requests:
            memory: 100Mi
            cpu: 50m
          limits:
            memory: 200Mi
            cpu: 100m
        ports:
        - containerPort: 5000